### ISSUE TITLE
Unable to pull main image

### ISSUE THREAD

**Issue by LarsStegman** [umati/Sample-Server#1035]
Hi,

we are trying to pull the `main` tagged image, but we get an error from docker:

```
> docker pull ghcr.io/umati/sample-server:main
main: Pulling from umati/sample-server
manifest unknown
```

From the looks of it, we are not the only ones, as the number of downloads in the past week has dropped significantly:

![image](https://user-images.githubusercontent.com/9332816/231165688-3582b435-6061-4acb-8c72-7e268964336d.png)

https://github.com/umati/Sample-Server/pkgs/container/sample-server/72795039?tag=main

**Comment by wlkrm** [comment]
Yes, its a regression. After the CI has run through, the develop tag should be working https://github.com/umati/Sample-Server/commits/develop

**Comment by LarsStegman** [comment]
Wow, that is a quick response. Thanks!
