### ISSUE TITLE
cmake fails

### ISSUE THREAD

**Issue by IOTeule** [umati/Sample-Server#290]
Hi, 
is it correct, that building the system without docker will fail ?

My output looks like:

-- Found PythonInterp: /usr/bin/python (found version "2.7.18") 
-- Found MbedTLS: /usr/include  
CMake Error at CMakeLists.txt:9 (find_package):
  By not providing "FindOpen62541Cpp.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Open62541Cpp", but CMake did not find one.

  Could not find a package configuration file provided by "Open62541Cpp" with
  any of the following names:

    Open62541CppConfig.cmake
    open62541cpp-config.cmake

  Add the installation prefix of "Open62541Cpp" to CMAKE_PREFIX_PATH or set
  "Open62541Cpp_DIR" to a directory containing one of the above files.  If
  "Open62541Cpp" provides a separate development package or SDK, be sure it
  has been installed.

**Comment by ccvca** [comment]
Either install all the dependencies from the deps folder manual, or use the _All in One_ CMake-Skript from the .github/ folder (Requires a writeable location for `CMAKE_INSTALL_PREFIX` ).

**Comment by IOTeule** [comment]
Thx for your support

**Comment by IOTeule** [comment]
There still seems to be an issue, if there is an existing open62541 installation.
cmake works on a system without existing open62541 installation, but fails with.

So it seems, cmake is using wrong version ?

Due to other reasons, I need to use local (from this repro) open62541 installation and NOT docker.

[ 95%] Performing build step for 'Sample-Server'
make[5]: *** Keine Regel vorhanden, um das Ziel „/usr/local/share/open62541/tools/ua-nodeset/DI/OpcUaDiModel.csv“, 
  benötigt von „../../src_generated/di_nodeids.h“, zu erstellen.  Schluss.
make[4]: *** [CMakeFiles/Makefile2:677: CMakeFiles/ua_gen_di.dir/all] Fehler 2
make[3]: *** [Makefile:141: all] Fehler 2

Any idea, how to fix cmake to only use local open62541 ?

**Comment by ccvca** [comment]
There migt be two possible reasons. Either CMake finds the wrong version, or the included headers are reference twice.
The first case cna be checked, by inverstigating the filled OPEN62541-Variables in CMake. A specific open62541-Installation can be selected by specifing open62541_DIR.
In the second case, the include <open62541/server.h> points to multiple headers with different versions. (e.g. /user/include/open62541/server and /home/dev/install/open62541/sever.h) as "/usr/include" is always in the included-Path the compiler might choose the wrong one. So the only solution is not to install open62541 globally. Any other solutions might be broken easily on updates.

**Comment by IOTeule** [comment]
Hey, thx a lot for answering.

NO, there is another dev constraint, so I HAVE to have a usr installation.

YES, cmake is always taking global installation.
Is there no way to adapt CMakeList.txt to the local deps/open62541 ?
There is already an open62541 in this repro, so how to force usage ?
I tried 

set(CMAKE_CXX_STANDARD 20)
set(open62541_DIR ${PROJECT_SOURCE_DIR}/deps/open62541)
set(open62541_NODESET_DIR ${PROJECT_SOURCE_DIR}/deps/open62541/deps/ua-nodeset)
set(open62541_TOOLS_DIR ${PROJECT_SOURCE_DIR}/deps/open62541/tools)

That does not change anything, if I run cmake -LAH, there are still the wrong path

**Comment by ccvca** [comment]
Have you cleared the CMake-Cache? I was thinking that setting `open62541_DIR` should force the local installation.

**Comment by IOTeule** [comment]
Sure, I tried several times with fresh clone. I am using All in One Script, but there are two parts of cmake, might this be the problem of caching ?

**Comment by IOTeule** [comment]
I just tried latest version from develop (156c36b), but it is still using local open62541 stuff, e.g. not finding robot types.
make[5]: *** Keine Regel vorhanden, um das Ziel „/usr/local/share/open62541/tools/ua-nodeset/Robotics/Opc.Ua.Robotics.Types.bsd“, 
  benötigt von „../../src_generated/types_robotics_generated.c“, zu erstellen.  Schluss.

So it still does not build this piece totally inside the build directory without external dependency ( here using public open62541) as expected.The missing file is in the repo, but not used (Sample-Server/deps/open62541/deps/ua-nodeset/Robotics/Opc.Ua.Robotics.Types.bsd).

Sorry, no progress.

**Comment by IOTeule** [comment]
<b>find_package</b> could be used in MODULE and CONFIG mode.
Is find_package(Foo CONFIG REQUIRED) a possible solution, see https://stackoverflow.com/questions/20746936/what-use-is-find-package-when-you-need-to-specify-cmake-module-path. But not sure how to set in this project.

**Comment by GoetzGoerisch** [comment]
Looking on the path example above `open62541/tools/ua-nodeset/` seams to be a problem with `open62541_NODESET_DIR` and `open62541_TOOLS_DIR`.
Could you investigate this?

**Comment by IOTeule** [comment]
decided to dev on virtual env
