### ISSUE TITLE
Server crash reading String Array

### ISSUE THREAD

**Issue by Kantiran91** [umati/Sample-Server#621]
Branch: dev_gms
If a client reads the value of the CalibrationCertificate the server crash. 
@ccvca: I tried to add the reflection for the string arrays see:
[(https://github.com/umati/Sample-Server/blob/7e2c60a75dce1263a6837052d98dfab23a97be8e/UmatiServerLib/ConvertSimpleValue.cpp#L34](https://github.com/umati/Sample-Server/blob/7e2c60a75dce1263a6837052d98dfab23a97be8e/UmatiServerLib/ConvertSimpleValue.cpp#L34)

I think the problem is there. See you the problem?

**Comment by ccvca** [comment]
https://github.com/umati/Sample-Server/blob/7e2c60a75dce1263a6837052d98dfab23a97be8e/UmatiServerLib/ConvertSimpleValue.cpp#L35
This is not valid C++, as the array dimensions are not fixed at compile time.

https://github.com/umati/Sample-Server/blob/7e2c60a75dce1263a6837052d98dfab23a97be8e/UmatiServerLib/ConvertSimpleValue.cpp#L37
A reference to a stack variable is stored in the anonmous function. But the memory will be used for othr things, after the function has been called.

`UA_Variant_setArrayCopy` does not handle size = 0.

**Comment by Kantiran91** [comment]
Thank you – We resolved the problem with commit 643f14686fad1c0b2bb7826d99236c67e46c3507
