### ISSUE TITLE
GMS: Possible Error in Server

### ISSUE THREAD

**Issue by wlkrm** [umati/Sample-Server#644]
The Results-Folder (BrowseName.Name: Results) seems to contain 2 elements.
With this workaround, the client works fine https://github.com/umati/Dashboard-OPCUA-Client/blob/0d4539c9574c745b6895d8eefa473d0bf5825175/DashboardClient/Converter/ModelToJson.cpp#L59.

**Comment by Kantiran91** [comment]
I cannot reproduce this issue. Is this still a problem?
