### ISSUE TITLE
BUG: LibreSSL 3.5.3 dev release does not build the server

### ISSUE THREAD

**Issue by GoetzGoerisch** [umati/Sample-Server#650]
See  branch https://github.com/umati/Sample-Server/tree/libre

https://github.com/umati/Sample-Server/runs/5466438550?check_suite_focus=true#step:5:1919

**Comment by GoetzGoerisch** [comment]
WIP: https://github.com/ccvca/open62541/tree/fix_libressl_3.5

**Comment by ccvca** [comment]
WIP-Branch should work, with the upcoming 3.5.4 release.

**Comment by GoetzGoerisch** [comment]
@ccvca this was supposed to be fixed by the latest libressl, but it does not fix the problem. Could you please have a look?

**Comment by ccvca** [comment]
TODO: These are the previous tries of fixes, which should resolve some errors: https://github.com/ccvca/open62541/tree/fix_libressl_3.5

**Comment by GoetzGoerisch** [comment]
@ccvca so rebase and create PR to open62541?

**Comment by ccvca** [comment]
The URI validation causes a SegFault. Already fixed upstream:
https://github.com/openbsd/src/commit/215e6767bc08f6f1f7de1bf68c9ef05ca9b21e78

Should work in the next release.

**Comment by GoetzGoerisch** [comment]
Thanks!
Bumped LibreSSL to 3.7.0 and rebased on open62541/master here: https://github.com/GoetzGoerisch/open62541/tree/fix_libressl_3.5
