### ISSUE TITLE
GMS SensorType example

### ISSUE THREAD

**Issue by ag-ctlg** [umati/Sample-Server#764]
Hi guys 👋 

I started working on the implementation of the Equipment->Tools part of the GMS companion spec and I am having trouble with finding an example implementation of the `SensorType` (subtype of `ToolType `from MachineTool NS).

All the example machines currently implemented in the Sample-Server use the `ToolType` and `MultiToolType` for Tools. Even machines derived from `GMSType`.

Would it be possible for someone to implement an example machine that uses all the types defined in the GMS spec?

That would be very helpful as I am using the Sample-Server as a reference.

Best regards,
Alen

**Comment by ag-ctlg** [comment]
I created a fork of the repository and made some changes in my free time. I have no idea whether I'm doing it right or not but [here's the link](https://github.com/mindonwarp/Sample-Server/tree/full_gms_machine) to the repo if someone who actually knows how to do this stuff wants to take a look and contribute. The branch is `full_gms_machine`

**Comment by GoetzGoerisch** [comment]
Hi Alen, thank you for your contribution.

The `SensorType `was not yet implemented due to resources. 
Looking forward to get this integrated.

**Comment by GoetzGoerisch** [comment]
Closed with #783 !

Thank you @mindonwarp for your contribution!
